baseURL = 'https://shulyak.xyz/'
languageCode = 'en-us'
title = 'Aliaksandr Shulyak'
theme = 'hugo-coder'


[pagination]
pagerSize = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "G-H6RZJKCK17"
disqusShortname = "AS"

[params]
  author = "Aliaksandr Shulyak"
  info = "Senoir Site Reliability Engineer | Team Lead"
  description = "Aliaksandr Shulyak's personal website"
  keywords = "blog,developer,personal,sre,swe"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2021

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false
  hideCredits = true
  hideCopyright = false

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ThelonKarrde"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/aliaksandr-shulyak/"
[[params.social]]
  name = "email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:alex@shulyak.xyz"

